export const BUNDLE_REASON_CODES = [
  "PRICE_DATA_STALE",
  "PRICE_DATA_TOO_STALE",
  "NEWS_DATA_STALE",
  "PARTIAL_DATA",
  "MISSING_CITATIONS",
  "CONFLICTING_EVIDENCE",
  "INVALID_TICKER",
  "INELIGIBLE_ACTION",
  "SCHEMA_INVALID_AFTER_REPAIR",
  "MODEL_EMPTY_RESPONSE",
  "SEMANTIC_VALIDATION_FAILED",
  "UNSUPPORTED_CERTAINTY",
  "CACHE_CORRUPTION",
  "CACHE_MISS",
  "CONVICTION_SNAPSHOT_INVALID",
  "PROFILE_SNAPSHOT_INVALID",
] as const;
export type BundleReasonCode = (typeof BUNDLE_REASON_CODES)[number];

export const ABSTAIN_REASON_CODES = [
  "PRICE_DATA_TOO_STALE",
  "MISSING_CITATIONS",
  "CONFLICTING_EVIDENCE",
  "INVALID_TICKER",
  "INELIGIBLE_ACTION",
  "SCHEMA_INVALID_AFTER_REPAIR",
  "MODEL_EMPTY_RESPONSE",
  "SEMANTIC_VALIDATION_FAILED",
  "UNSUPPORTED_CERTAINTY",
  "CACHE_CORRUPTION",
  "CONVICTION_SNAPSHOT_INVALID",
  "PROFILE_SNAPSHOT_INVALID",
] as const;
export type AbstainReasonCode = (typeof ABSTAIN_REASON_CODES)[number];

export const DEGRADED_REASON_CODES = [
  "PRICE_DATA_STALE",
  "NEWS_DATA_STALE",
  "PARTIAL_DATA",
  "CACHE_MISS",
] as const;
export type DegradedReasonCode = (typeof DEGRADED_REASON_CODES)[number];

export const RUN_FAILURE_CODES = [
  "INPUT_FREEZE_FAILED",
  "EVIDENCE_BUILD_TIMEOUT",
  "MODEL_TRANSPORT_FAILURE",
  "MODEL_TIMEOUT",
  "PERSISTENCE_WRITE_FAILED",
  "UNHANDLED_EXCEPTION",
] as const;
export type RunFailureCode = (typeof RUN_FAILURE_CODES)[number];

export const DELIVERY_ERROR_CODES = [
  "SMTP_TRANSIENT_FAILURE",
  "SMTP_PERMANENT_FAILURE",
  "RECIPIENT_REJECTED",
  "AUTH_FAILURE",
  "UNKNOWN_DELIVERY_ERROR",
] as const;
export type DeliveryErrorCode = (typeof DELIVERY_ERROR_CODES)[number];
